### PR TITLE
Toolbar

### PR DESCRIPTION
**Pull request by petuomin**

### CODE REVIEW

**Comment by ammsalme** [comment]
Emptying all by clicking 'Uusi' leaves 'Yhdistä' -button active.
Clicking 'Yhdistä' -button after this causes "Uncaught TypeError: Cannot read property 'filter' of undefined" -error.

**"OK"**

**Comment by ammsalme** [comment]
Inconsistency in functionality: "Skip" -function empties workspace "Not double" does not.

**OK**

**Comment by ammsalme** [comment]
"Skip" and "Not double" could maybe also fetch the next double straight away?

**OK**

**Comment by ammsalme** [comment]
"Next" fetches the same double again, if current double is not resolved. 

**OK**

**Comment by ammsalme** [comment]
Records are opened containing only empty LDR if they do not exist in the database.

API returns:

`<error>Error reading document</error>`

**OK**

**Comment by petuomin** [comment]
`"Next" fetches the same double again, if current double is not resolved.`

This is the way it should work. The next one in the queue is loaded with next. If user does not want to handle it, it can be skipped.

**Pull request merged**
